export default {
  /*
   *
   *  USER CONSTANTS
   */
  CREATE_USER: 'CREATE_USER',
  SIGN_IN_USER: 'SIGN_IN_USER',
  CONFIRM_USER: 'CONFIRM_USER',
  SIGN_OUT_USER: 'SIGN_OUT_USER',
  GET_CURRENT_USER: 'GET_CURRENT_USER',

  /*
   *
   *  UNAUTHENTICATED USER SESSION CONSTANTS
   */
  SUBMIT_USER_WELCOME_DATA: 'SUBMIT_USER_WELCOME_DATA',
  SUBMIT_ADDRESS_FORM_DATA: 'SUBMIT_ADDRESS_FORM_DATA',
  SUBMIT_VEHICLE_FORM_DATA: 'SUBMIT_VEHICLE_FORM_DATA',
  SUBMIT_DRIVER_FORM_DATA: 'SUBMIT_DRIVER_FORM_DATA',
  SUBMIT_FINAL_FORM_DATA: 'SUBMIT_FINAL_FORM_DATA',

  /*
   *
   *  HERO IMAGE CONSTANTS
   */
  CHANGE_HERO_IMAGE: 'CHANGE_HERO_IMAGE'
};
